name: Restrict PR Sources to Main

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  restrict-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source Branch
        run: |
          TARGET_BRANCH=${{ github.base_ref }}
          SOURCE_BRANCH=${{ github.head_ref }}

          if [ "$TARGET_BRANCH" = "main" ]; then
            if [ "$SOURCE_BRANCH" != "staging" ]; then
              echo "Error: Pull requests to 'main' can only come from 'staging'."
              exit 1
            fi
          fi
