name: SONAR TEST
on:
  push:
    branches:
      - staging  # Trigger on pushes to the staging branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - staging  # Trigger on pull requests targeting the staging branch

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
