name: SonarCloud Analysis

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/latest/linux
          unzip sonar-scanner.zip  # Extract the downloaded zip file
          mv sonar-scanner sonar-scanner-<version>  # Optional: Rename scanner with version

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
        run: |
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=arun-j0_CICD-1 \
            -Dsonar.organization=arun-j0 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.version=3.10.12 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}